{{- include "nzbget.validateValues.auth" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nzbget.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "nzbget.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nzbget.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
{{- with (include "nzbget.imagePullSecrets" .) }}
{{- . | nindent 6 }}
{{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}
      initContainers:
        - name: copy-nzbget-config
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: busybox
          env:
            - name: PUID
              value: {{ .Values.containerSecurityContext.runAsUser | default 1000 | quote }}
            - name: PGID
              value: {{ .Values.containerSecurityContext.runAsGroup | default 1000 | quote }}
          command:
            - sh
            - -c
            - >
                echo "PUID=$PUID, PGID=$PGID" &&
                cp -v /temp/nzbget.conf /config/nzbget.conf &&
                chown "${PUID}:${PGID}" /config/nzbget.conf &&
                chmod 664 /config/nzbget.conf &&
                ls -l /config
          volumeMounts:
            - name: nzbget-temp-config
              mountPath: /temp/nzbget.conf
              subPath: nzbget.conf
            {{- if .Values.persistence.enabled }}
            - name: nzbgetconfigfolder
              mountPath: /config
            {{- end }}
            {{- if .Values.extraVolumes }}
            {{- range $storage := .Values.extraVolumes }}
            - name: {{ $storage.name }}
              mountPath: {{ $storage.mountPath }}
            {{- end }}
            {{- end }}
            {{- if .Values.nfsVolumes }}
            {{- range $nfsstorage := .Values.nfsVolumes }}
            - name: {{ $nfsstorage.name }}
              mountPath: {{ $nfsstorage.mountPath }}
            {{- end }}
            {{- end }}
      containers:
        - name: nzbget
          image: {{ include "nzbget.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
            {{- if .Values.auth.existingSecret }}
            - name: NZBGET_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.userNameKey }}
            - name: NZBGET_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.userPasswordKey }}
            {{- else}}
            - name: NZBGET_USER
              value: {{ .Values.auth.username | quote }}
            - name: NZBGET_PASS
              value: {{ include "chrt-6456.password" . | quote }}
            {{- end }}
          ports:
            - name: nzbget-http
              containerPort: {{ .Values.service.port | default 6789 }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- $probe := merge (omit .Values.livenessProbe "enabled") (dict "tcpSocket" (dict "port" (.Values.service.port | default 6789))) }}
            {{- $probe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- $probe := merge (omit .Values.readinessProbe "enabled") (dict "tcpSocket" (dict "port" (.Values.service.port | default 6789))) }}
            {{- $probe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- $probe := merge (omit .Values.startupProbe "enabled") (dict "tcpSocket" (dict "port" (.Values.service.port | default 6789))) }}
            {{- $probe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: nzbgetconfigfolder
              mountPath: /config
            {{- end }}
            {{- if .Values.extraVolumes }}
            {{- range $storage := .Values.extraVolumes }}
            - name: {{ $storage.name }}
              mountPath: {{ $storage.mountPath }}
            {{- end }}
            {{- end }}
            {{- if .Values.nfsVolumes }}
            {{- range $nfsstorage := .Values.nfsVolumes }}
            - name: {{ $nfsstorage.name }}
              mountPath: {{ $nfsstorage.mountPath }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.config.existingConfigMap }}
        - name: nzbget-temp-config
          configMap:
            name: {{ .Values.config.existingConfigMap }}
            items:
            - key: nzbget.conf
              path: nzbget.conf
        {{- end }}
        {{- if .Values.config.existingSecret }}
        - name: nzbget-temp-config
          secret:
            secretName: {{ .Values.config.existingSecret }}
            items:
            - key: nzbget.conf
              path: nzbget.conf
        {{- else if (.Values.config.useExternalSecret) }}
        - name: nzbget-temp-config
          secret:
            secretName: {{ include "nzbget.fullname" . }}-config
            items:
            - key: nzbget.conf
              path: nzbget.conf
        {{- end }}
        {{- range $secret := .Values.extraSecrets }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.name }}
            defaultMode: {{ $secret.defaultMode | default 0440 }}
        {{- end }}
        {{- range $storage := .Values.extraVolumes }}
        - name: {{ $storage.name }}
          persistentVolumeClaim:
            claimName: {{ $storage.pvcName }}
        {{- end }}
        {{- range $nfsstorage := .Values.nfsVolumes }}
        - name: {{ $nfsstorage.name }}
          nfs:
            server: {{ $nfsstorage.nfs.server }}
            path: {{ $nfsstorage.nfs.path }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.metrics.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "nzbget.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbget-exporter.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "nzbget-exporter.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nzbget-exporter.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: nzbget-exporter
          image: {{ .Values.metrics.image.registry }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          imagePullPolicy: {{ .Values.metrics.image.imagePullPolicy }}
          args:
            - nzbget
          env:
            - name: NZBGET_HOST
              value: "http://{{ include "nzbget.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port | default 6789 }}"
            {{- if .Values.auth.existingSecret }}
            - name: NZBGET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.userNameKey }}
            - name: NZBGET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.userPasswordKey }}
            {{- else}}
            - name: NZBGET_USERNAME
              value: {{ .Values.auth.username | quote }}
            - name: NZBGET_PASSWORD
              value: {{ include "chrt-6456.password" . | quote }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.containerPort | default 9707 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
