{{- if .Values.config.useExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "nzbget.fullname" . }}-config
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: {{ .Values.config.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.config.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "nzbget.fullname" . }}-config
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ include "nzbget.fullname" . }}
          # here you define the keys that should be used as template
          items:
          - key: nzbget.conf
            templateAs: Values
        target: Data
  data:
{{- range $secret := .Values.config.externalSecret.data }}
  - secretKey: {{ $secret.secretKey }}
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secret.key }}
      metadataPolicy: None
{{- end }}
{{- end }}
