apiVersion: v1
kind: Service
metadata:
  name: {{ include "nzbget.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nzbget-http
      protocol: TCP
      name: nzbget-http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "nzbget.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nzbget.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbget-exporter.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.metrics.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "nzbget-exporter.labels" . | nindent 4 }}
{{- end }}
