apiVersion: v2
name: lidarr
description: Lidarr is a music collection manager for Usenet and BitTorrent users.
type: application
version: 0.0.6
appVersion: "25.3.20250926"

sources:
  - https://hub.docker.com/r/linuxserver/lidarr

dependencies:
  - name: common
    version: 1.x.x
    repository: "https://pascal0030.github.io/helm-charts/"
