{{- if .Values.route.main.enabled }}
{{- $fullName := include "sonarr.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "sonarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs: {{ .Values.route.main.parentRefs | toYaml | nindent 4 }}
  hostnames: {{ .Values.route.main.hostnames | toYaml | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          kind: Service
          group: ''
          port: {{ $svcPort }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
