apiVersion: v2
name: nzbget
description: NZBGet is a lightweight and efficient Usenet downloader
type: application
version: 0.0.13
appVersion: "25.3.20250926"

sources:
  - https://hub.docker.com/r/linuxserver/nzbget

dependencies:
  - name: common
    version: 1.x.x
    repository: "https://pascal0030.github.io/helm-charts/"
